#!/usr/bin/env bash
# Idempotent bootstrap for the FastBird / Yum-Mi dev environment.
# Safe to run repeatedly (Cloud Agent `install` phase or local setup).
set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> Installing dependencies"
npm install

# Ensure a local .env exists with sensible development defaults.
# Secrets injected as real environment variables (e.g. DATABASE_URL) take
# precedence and are not overwritten here.
if [ ! -f .env ]; then
  echo "==> Creating .env with development defaults"
  {
    echo "# Auto-generated by scripts/cloud-agent-install.sh"
    echo "USE_CLERK_MOCK=\"1\""
    if [ -n "${DATABASE_URL:-}" ]; then
      echo "DATABASE_URL=\"${DATABASE_URL}\""
    fi
  } > .env
fi

echo "==> Generating Prisma client"
npx prisma generate

# Push schema only when a database URL is available.
DB_URL="${DATABASE_URL:-}"
if [ -z "$DB_URL" ] && grep -q '^DATABASE_URL=' .env 2>/dev/null; then
  DB_URL="$(grep '^DATABASE_URL=' .env | head -1 | cut -d= -f2- | tr -d '"')"
fi

if [ -n "$DB_URL" ]; then
  echo "==> Syncing database schema (prisma db push)"
  npx prisma db push --skip-generate
else
  echo "==> DATABASE_URL not set — skipping prisma db push (DB features will be unavailable until it is provided as a secret)"
fi

echo "==> Install complete"
